version: '3.7'

services:
  oracle-db:
    container_name: oracle-db
    image: gvenzl/oracle-xe
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: 123456a
      ORACLE_DATABASE: lucid
      APP_USER: lucid
      APP_USER_PASSWORD: lucid
